# Generated by Django 4.0 on 2022-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_thumbnail_alter_blogpost_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='count_comments',
            field=models.IntegerField(default=0),
        ),
    ]
